name: infortts_shared
description: Shared high-performance, minimalist UI components and themes for Infortts.
version: 1.0.0
repository: https://github.com/InforttsOrg/project-shared
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  flutter_animate: ^4.5.2
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
